### PR TITLE
Modernization

### LINKED ISSUE #3: redo the initialization/setup/stop logic based on the QtPlugin
As mentioned on:

https://github.com/TheCrazyT/x64dbg-plugin-quickaccess/issues/1

### LINKED ISSUE #4: do you have 32bit ?
do you have 32bit ?

### PR DESCRIPTION
**Pull request by mrexodia**
- There is now a QuickAccess class that's responsible for everything
- Fixed a few bugs related to the GUI thread (no longer crashes on exit)
- Greatly simplify the code
- Allow fuzzy search instead of exact matching (let me know if you don't prefer this)

Closes #4 
Closes #3

### CODE REVIEW

**Comment by TheCrazyT** [comment]
Thanks for your pull request.
But sadly I can't merge it the way it currently is.

There is no way to review those binary-files in the pluginsdk-folder.
(There is no way to figure out if they are good or evil.
And since I don't know you, I don't trust them.)

Maybe modify the pull-request to have them not included?

Note to myself:
I keep this pull request open, maybe I find another way to merge without polluting my repo with unknown binaries ...

**Comment by mrexodia** [comment]
I’m the creator of x64dbg, they come from my dev machine. But I can copy them from any snapshot you prefer (they are also coming from that same machine though 😅).

**Comment by TheCrazyT** [comment]
@mrexodia 

> I’m the creator of x64dbg

Oops, sorry, I didn't see that!
This changes everything!

Guess an improvement would be if I could just somehow use a git-submodule for the pluginsdk.

**Comment by mrexodia** [comment]
With CMake you can set it up to automatically download a snapshot and use the `pluginsdk` from there: https://github.com/x64dbg/PluginTemplate/blob/main/cmake/x64dbg.cmake. You cannot directly use the x64dbg repo as a submodule because that doesn't contain the necessary `.lib` files.

Currently there is no CMake template for a Qt plugin, I'll consider making it.

**Pull request merged**
